name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.7
    with:
      templateVersion: 0.10.7
      rg: rg-aks-ec-01
      resourceName: akc-ec-01
      templateParams: resourceName=akc-ec-01 managedNodeResourceGroup=rg-aks-mgmt-ec-01 agentCount=1 upgradeChannel=stable AksPaidSkuForSLA=true agentVMSize=Standard_B4s_v2 nodePoolName=ecpool01 osDiskType=Managed byoAKSSubnetId=/subscriptions/37220b7b-6bd3-4f11-b4db-37e24f3698a4/resourceGroups/rg-ec-aks-spoke-connectivity/providers/Microsoft.Network/virtualNetworks/vnet-spoke-aks-01/subnets/snet-spoke-aks-nodes-01 serviceCidr=10.60.100.0/24 dnsServiceIP=10.60.100.10 byoAKSPodSubnetId=/subscriptions/37220b7b-6bd3-4f11-b4db-37e24f3698a4/resourceGroups/rg-ec-aks-spoke-connectivity/providers/Microsoft.Network/virtualNetworks/vnet-spoke-aks-01/subnets/snet-spoke-aks-pods-01 enable_aad=true AksDisableLocalAccounts=true enableAzureRBAC=true adminPrincipalId=_USER_OBJECT_ID_ registries_sku=Basic acrPushRolePrincipalId=_USER_OBJECT_ID_ enableTelemetry=false omsagent=true retentionInDays=30 azurepolicy=deny cniDynamicIpAllocation=true availabilityZones=["1","2","3"] maxPods=250 enablePrivateCluster=true keyVaultAksCSI=true warIngressNginx=true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
