name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.7
    with:
      templateVersion: 0.10.7
      rg: rg-ec-aks
      resourceName: ec-01
      templateParams: resourceName=ec-01 managedNodeResourceGroup=rg-ec-aks-mgmt agentCount=1 upgradeChannel=stable AksPaidSkuForSLA=true agentVMSize=Standard_B4s_v2 nodePoolName=ecpool01 osDiskType=Managed byoAKSSubnetId=/subscriptions/37220b7b-6bd3-4f11-b4db-37e24f3698a4/resourceGroups/rg-ec-aks-spoke-connectivity/providers/Microsoft.Network/virtualNetworks/vnet-spoke-aks-01/subnets/snet-spoke-nodes-aks-01 enable_aad=true AksDisableLocalAccounts=true enableAzureRBAC=true adminPrincipalId=_USER_OBJECT_ID_ registries_sku=Premium acrPushRolePrincipalId=_USER_OBJECT_ID_ omsagent=true retentionInDays=30 serviceMeshProfile=NaN azurepolicy=audit networkPluginMode=Overlay availabilityZones=["1","2","3"] maxPods=250 enablePrivateCluster=true keyVaultAksCSI=true keyVaultCreate=true keyVaultOfficerRolePrincipalId=_USER_OBJECT_ID_ warIngressNginx=true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
